# https://kubernetes.io/docs/user-guide/services/
# https://kubernetes.io/docs/api-reference/v1/definitions/#_v1_service
# Kubernetes supports multiple virtual clusters backed by the same physical cluster.
# These virtual clusters are called namespaces.
# https://kubernetes.io/docs/api-reference/v1/definitions/#_v1_servicespec
# https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/

kind: Service
apiVersion: v1
metadata:
  name: "helloworld"
  namespace: "dev" # prod, staging
spec:
  selector:
    app: "helloworld"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  # "type": "LoadBalancer" # only in namespace; prod