apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    app: nginx
    tier: frontend
    track: stable # canary
    environment: dev # prod,
    # role: master
spec:
  # type: LoadBalancer, only in production
  ports:
  - port: 80
  selector:
    app: nginx
    tier: frontend
